# Generated by Django 2.0.5 on 2018-06-04 08:12

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_attendence', jsonfield.fields.JSONField()),
                ('date', models.DateTimeField()),
                ('session_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faceRecognition.Session')),
            ],
        ),
    ]
